### ISSUE TITLE
Question 25 in objective 1.2 incorrect (Defining virtual directory/virtual application mapping in new portal)

### ISSUE THREAD

**Issue by bobleith** [crpietschmann/Azure-70-532-Practice-Test#4]
The correct answer reflects steps for defining a custom domain in preview portal and the choices do not present an answer to meeting the objective for a virtual directory.

What are the steps for defining a Virtual Directory or Virtual Application mapping in the preview portal?
Navigate to the management portal at https://manage.windowsazure.com
Navigate to the management portal at https://portal.azure.com
Navigate to the blade for the Azure Web App
Click "All settings" link to open the Settings blade
Click on the "manage domains" button
Click "Custom domains and SSL" to open the Web App custom domains and SSL blade

**Comment by crpietschmann** [comment]
When I originally created these questions I hadn't taken the exam yet. Since taking the exam, I now know the actual Portal UI's aren't covered on the exam, but rather the concepts and order of operations to configure things. It's on my list to redo the Portal UI questions as a result.

**Comment by crpietschmann** [comment]
No longer relevant as the questions need to be updated to reflect recent changes to the platform.
