### ISSUE TITLE
Clicking on links and then going back loses context

### ISSUE THREAD

**Issue by bobleith** [crpietschmann/Azure-70-532-Practice-Test#5]
Enhancement suggestion: When clicking on a link provided at the bottom of a question such as the link for the full source for the exam, the URL does not open in a new window and going back takes you all the way back to the start of the exam so all answers in the objective are lost. It would be better to open URLs in a new window by default rather than forcing the user to remember to use "open in new tab or window"

**Comment by crpietschmann** [comment]
This is an excellent suggestion. Thanks!

**Comment by bobleith** [comment]
Thanks for the quick response. BTW, I really appreciate your creating this practice test. I haven't taken the exam yet, but this seems to align well with the objectives outlined for the exam and a great prep tool.

**Comment by crpietschmann** [comment]
Fixed!

Sorry it took so long for me to finally fix it. I really appreciate the feedback.
