### ISSUE TITLE
Question 4 in Objective Deploy and manage virtual machines  - Wrong answer and unsuitable valid choices

### ISSUE THREAD

**Issue by bobleith** [crpietschmann/Azure-70-532-Practice-Test#6]
All of the choices are indicated as correct answers, but there is no virtual machines section and none of the choices actually selects a virtual machine with the current version of the preview portal. (You need to simply click on the image you want rather than using marketplace - there is no "virtual machines" section - the selections are grouped by platform or functionality type of server (i.e. database server, Windows based,  Linux-based, Security + Protection, etc.)

What are the steps for creating a Windows Virtual Machine within the Preview Portal?
Navigate to the management portal at https://manage.windowsazure.com
Navigate to the management portal at https://portal.azure.com
Click "New", the "Compute"
Click "Azure Marketplace" to open up the Marketplace blade
Scroll down to the "Virtual Machines" section and select "Windows Server"
Select the version of Windows Server desired and click "Create"
Enter the VM settings and click "Create

**Comment by crpietschmann** [comment]
When I originally created these questions I hadn't taken the exam yet. Since taking the exam, I now know the actual Portal UI's aren't covered on the exam, but rather the concepts and order of operations to configure things. It's on my list to redo the Portal UI questions as a result.

**Comment by crpietschmann** [comment]
I removed these Portal UI questions. The exams don't focus on the specific Portal UI, but rather the steps required and what order.
