### ISSUE TITLE
Question 2 in Create and manage virtual machines - wrong answer

### ISSUE THREAD

**Issue by bobleith** [crpietschmann/Azure-70-532-Practice-Test#7]
All the choices should be correct even though the correct answer indicates only Windows Server 2008, 2012, and 2012 R2, since the question asks for what versions are supported as Azure virtual machines, and not which versions are available in the market place. Reference: https://support.microsoft.com/en-us/kb/2721672
The question either needs to state which versions are available in the Marketplace or require all choices to be selected.
Which Windows Server versions are supported as Azure Virtual Machines?
Windows Server 2003
Windows Server 2008
Windows Server 2008 R2
Windows Server 2012
Windows Server 2012 R2

**Comment by crpietschmann** [comment]
Win 2003 requires a CSA and is not in the marketplace. This question will need to be reworded, in addition to adding another new question so the topic is covered well enough.

Thanks for reporting this!

**Comment by crpietschmann** [comment]
I reworded the question for now. Thanks!
